
[[constraint]]
  name = "github.com/bitly/go-simplejson"
  version = "0.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/google/gops"
  version = "0.3.2"

[[constraint]]
  branch = "master"
  name = "github.com/kitech/go-toxcore"

[[constraint]]
  branch = "master"
  name = "github.com/kitech/godsts"

[[constraint]]
  name = "github.com/nats-io/gnatsd"
  version = "1.0.4"

[[constraint]]
  name = "github.com/nats-io/nats"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/image"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gomatcha.io/matcha"
  version = "0.2.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.8.2"
